export const EN_TEXTS = {
  accederFacturas: 'Access Invoices',
  pedirCita: 'Book an Appointment',
  iniciarSesion: 'Sign In',
  email: 'Email',
  placeholderEmail: 'Enter your email',
  emailRequerido: 'Email is required',
  emailValido: 'Enter a valid email address',
  contrasena: 'Password',
  placeholderContrasena: 'Enter your password',
  contrasenaRequerida: 'Password is required',
  contrasenaMinimo: 'Password must be at least 6 characters',
  iniciandoSesion: 'Signing in...',
  noTienesCuenta: "Don't have an account?",
  creaCuenta: 'Create one here',
  errorIniciarSesion: 'Error signing in. Please check your details.',
  demasiadosIntentos: 'Too many attempts. Please wait 30 minutes.',
  errorServidor: 'Error connecting to the server.',
  camposIncorrectos: 'Please complete all fields correctly.',
  // Register texts
  registro: 'Register',
  nombreCompleto: 'Full Name',
  confirmarContrasena: 'Confirm Password',
  metodoNotificacion: 'Notification Method',
  seleccionaMetodo: 'Select a method',
  telefonoSMS: 'Phone for SMS',
  usuarioTelegram: 'Telegram Username',
  telefonoWhatsApp: 'Phone for WhatsApp',
  contacto: 'Contact',
  registrando: 'Registering...',
  registrarse: 'Register',
  yaTienesCuenta: 'Already have an account?',
  iniciaSesion: 'Sign in',
  errorRegistro: 'Error registering. Please try again.',
  errorConexion: 'Error connecting to the server.',
  campoRequerido: 'This field is required',
  minCaracteres: 'Must be at least {min} characters',
  contrasenasNoCoinciden: 'Passwords do not match',
  // Chat texts
  CHAT: {
    TITULO: 'Conversations',
    NUEVO_CHAT: 'New Chat',
    NO_MENSAJES: 'No messages',
    ESCRIBIR_MENSAJE: 'Type a message...',
    ENVIAR: 'Send',
    SELECCIONAR_CONVERSACION: 'Select a conversation to start',
    SELECCIONAR_TALLER: 'Select Workshop',
    BUSCAR_TALLER: 'Search workshop...'
  },
  home: {
    welcome: "Welcome to AutocareHub!",
    subtitle: "The easy way to take care of your car"
  },
  menu: {
    makeAppointment: 'Make Appointment',
    registerVehicle: 'Register Vehicle',
    invoiceViewer: 'View Invoices',
    chat: 'Chats',
    invoiceGenerator: 'Generate Invoice',
    viewAppointments: 'View Appointments',
    statistics: 'Statistics'
  }
};