export const ES_TEXTS = {
  accederFacturas: 'Acceder a Facturas',
  pedirCita: 'Pedir una Cita',
  iniciarSesion: 'Iniciar Sesión',
  email: 'Correo electrónico',
  placeholderEmail: 'Introduce tu correo electrónico',
  emailRequerido: 'El correo electrónico es obligatorio',
  emailValido: 'Introduce un correo electrónico válido',
  contrasena: 'Contraseña',
  placeholderContrasena: 'Introduce tu contraseña',
  contrasenaRequerida: 'La contraseña es obligatoria',
  contrasenaMinimo: 'La contraseña debe tener al menos 6 caracteres',
  iniciandoSesion: 'Iniciando sesión...',
  noTienesCuenta: '¿No tienes cuenta?',
  creaCuenta: 'Crea una aquí',
  errorIniciarSesion: 'Error al iniciar sesión. Verifica tus datos.',
  demasiadosIntentos: 'Demasiados intentos. Por favor, espera 30 minutos.',
  errorServidor: 'Error al conectar con el servidor.',
  camposIncorrectos: 'Por favor, completa todos los campos correctamente.',
  // Textos de registro
  registro: 'Registro',
  nombreCompleto: 'Nombre completo',
  confirmarContrasena: 'Confirmar contraseña',
  metodoNotificacion: 'Método de notificación',
  seleccionaMetodo: 'Selecciona un método',
  telefonoSMS: 'Teléfono para SMS',
  usuarioTelegram: 'Usuario de Telegram',
  telefonoWhatsApp: 'Teléfono para WhatsApp',
  contacto: 'Contacto',
  registrando: 'Registrando...',
  registrarse: 'Registrarse',
  yaTienesCuenta: '¿Ya tienes cuenta?',
  iniciaSesion: 'Inicia sesión',
  errorRegistro: 'Error al registrar. Inténtalo de nuevo.',
  errorConexion: 'Error de conexión con el servidor.',
  campoRequerido: 'Este campo es obligatorio',
  minCaracteres: 'Debe tener al menos {min} caracteres',
  contrasenasNoCoinciden: 'Las contraseñas no coinciden'
};